### ISSUE TITLE
Verify builds on other machines

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#79]

**Comment by kanerogers** [comment]
@pwcl Could you please try a build on Linux? It will almost certainly fail but it'll be fun to find out why.

**Comment by sinoth** [comment]
On Windows, trying to run `cargo apk run --release` in `examples\beat-saber-clone` results in:
```
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing, e.g., `--lib` or `--bin NAME` to specify a single target
Error: Command `cargo rustc --target aarch64-linux-android --release -- -L F:\\Rust\\hotham\\target\\cargo-apk-temp-extra-link-libraries` had a non-zero exit code.
```

**Comment by kanerogers** [comment]
Thanks so much to @sinoth for finding these issues!

1. Need to make sure the user has Android SDK and Android NDK installed.
1.1. Make sure they're using NDK22 as NDK23 has issues with `android-ndk-glue`: https://github.com/rust-windowing/android-ndk-rs/pull/189
2.

**Comment by pierre-l** [comment]
> Could you please try a build on Linux? It will almost certainly fail but it'll be fun to find out why.
Hey, this project looks awesome, pretty much exactly what I was looking for :)

I gave it a try yesterday. I had to replace both *.so for it to compile, and chmod +x. Unfortunately the activity never starts on the headset, it keeps loading. I didn't use the `--release` arg though. I'll try that soon.

**Comment by sinoth** [comment]
> Unfortunately the activity never starts on the headset, it keeps loading.

@pierre-l Did you get a black screen? If so, running try emulating what the run_on_device.ps1 script in the project root is doing. Using something like `adb shell pidof rust.beat_saber_example` then `adb logcat --pid=###` where ### is the Process ID returned from the first command.

This will allow you to see if/how the app is crashing. In my case, it was an error with the most recent crate of OpenXR and the version of ndk-glue being requested. @kanerogers pushed a fix very recently for this. Try pulling the most recent commit to see if it helps.

**Comment by pierre-l** [comment]
@sinoth I get a panic from `ndk-glue`. I still have to use the `*.so`s I downloaded myself to compile successfully but maybe I don't have the right version of these. Do you have any recommendation?

```
--------- beginning of main
01-08 14:37:54.150 12014 12014 I t_saber_exampl: Late-enabling -Xcheck:jni
01-08 14:37:54.185 12014 12014 E t_saber_exampl: Unknown bits set in runtime_flags: 0x8000
01-08 14:37:54.245 12014 12014 W System  : ClassLoader referenced unknown path: 
01-08 14:37:54.338 12014 12038 I RustStdoutStderr: [BEAT_SABER_EXAMPLE] MAIN!
01-08 14:37:54.345 12014 12038 I RustStdoutStderr: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-glue-0.5.0/src/lib.rs:59:39
01-08 14:37:54.345 12014 12038 I RustStdoutStderr: stack backtrace:
01-08 14:37:54.345 12014 12038 I RustStdoutStderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
[Bash script draft](https://github.com/pierre-l/hotham/commit/6c8dc59290473248beb6d0e9378976e1ca0b6306)

**Comment by sinoth** [comment]
@pierre-l This is exactly the error I was getting before @kanerogers updated the `ndk-glue` version. The problem was something along the lines of one part of the code using version `0.4.0` and another using `0.5.0`. Hopefully @kanerogers can come to the rescue here! You might try using version `0.4.0` if you can.

**Comment by pierre-l** [comment]
@sinoth I was using the Oculus mobile SDK v35. Rolling back to v34 allowed me to go further.
The panick now occurs upon texture loading:
```
01-08 15:15:59.199 12995 13020 I RustStdoutStderr: [HOTHAM_RENDERER] Creating renderer..
01-08 15:15:59.199 12995 13020 I RustStdoutStderr: [HOTHAM_INIT] Creating swapchain....done!
01-08 15:15:59.200 12995 13020 I RustStdoutStderr: [HOTHAM_INIT] Creating render pass....done!
01-08 15:15:59.432 12995 13020 I RustStdoutStderr: [HOTHAM_INIT] Creating pipeline..[HOTHAM_INIT] Creating frames.. ..done!
01-08 15:15:59.432 12995 13020 I RustStdoutStderr: [HOTHAM_RENDERER] Creating UBO..
01-08 15:15:59.432 12995 13020 I RustStdoutStderr: [HOTHAM_VULKAN] Allocated 288 bits of buffer memory: 0xb097c90000000027
01-08 15:15:59.432 12995 13020 I RustStdoutStderr: [HOTHAM_VULKAN] Allocated 40 bits of buffer memory: 0xb9181f0000000029
01-08 15:15:59.432 12995 13020 I RustStdoutStderr: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownFileFormat', hotham/src/texture.rs:206:10
```
Investigating...

**Comment by kanerogers** [comment]
Holy smokes @pierre-l ! Thanks so much for checking out Hotham and big thanks to @sinoth for helping out! Sorry it took me a while to reply - I try to take at least Saturday off. 😄 

@pierre-l can I ask what example you're trying to run that's giving you the texture error? Potentially it's one of the older ones that I haven't been keeping up to date. 

If you try the beat saber example, that's usually the most up to date and stable. It won't show you the game at the moment, but it will give you a UI test, and importantly, it should build.

If you're still having issues, let me know and I can investigate further!

**Comment by kanerogers** [comment]
> @sinoth I was using the Oculus mobile SDK v35. Rolling back to v34 allowed me to go further.

Interesting! I've been hand building libopenxr rather than using the Oculus SDK. I'll check this out!

**Comment by pierre-l** [comment]
I hadn't enabled LFS, sorry! I'm now able to get even further without having to change any `*.so`.

Another panic, but I feel close!
```
1-09 01:54:49.493  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] Allocated 8260 bits of buffer memory: 0xad5092000000018d
01-09 01:54:49.493  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] Allocating mesh descriptor sets..
01-09 01:54:49.493  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] ..done! [0x296268000000018e]
01-09 01:54:49.494  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] Allocated 8260 bits of buffer memory: 0x7a6b0c0000000190
01-09 01:54:49.494  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] Allocating mesh descriptor sets..
01-09 01:54:49.494  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] ..done! [0x42878f0000000191]
01-09 01:54:49.494  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] Allocated 8260 bits of buffer memory: 0x4557cc0000000193
01-09 01:54:49.494  6097  6120 I RustStdoutStderr: [HOTHAM_VULKAN] Allocating mesh descriptor sets..
01-09 01:54:49.494  6097  6120 I RustStdoutStderr: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_OUT_OF_POOL_MEMORY', hotham/src/gltf_loader.rs:367:10
```

**Comment by kanerogers** [comment]
No need to apologise @pierre-l ! I provided no documentation whatsoever, the fact that you've made it this far is a miracle!

Just to confirm: which example are you running and on what device?

**Comment by pierre-l** [comment]
@kanerogers I'm running the beat saber example on the original Oculus Quest

**Comment by kanerogers** [comment]
Aha, that may be the issue. Potentially the number of descriptors is lower on the Quest 1: I haven't run any of the more recent demos on it in a while. 

Descriptor pool sizes still needs to be set correctly: from memory I just set them to whatever value will make a given scene work. I had recently tested the Quest 2 on some very complex scenes, so potentially that's why the number is so high right now. 

I'll take a look on my Quest 1 tonight, but in the meantime if you want to just get something around, take a look in `VulkanContext` constructor and see if you can find a descriptor pool that has a very high number (eg. > 100). Without looking at it I think the sampler pool was bumped recently. Tweak it around a bit and see what happens. 😄 

Long term the solution should be to have a more programmatic pool size: either the max size the device will give us, or perhaps based on an analysis of the scene.

**Comment by pierre-l** [comment]
No luck with 10/100/1000 values :'(

**Comment by kanerogers** [comment]
Rats! I ran out of time yesterday @pierre-l but I'll make sure I get onto this today!

**Comment by kanerogers** [comment]
@pierre-l PS. @sinoth suggested I create a Hotham Discord - please feel free to jump in if you want to get some realtime support on Hotham: https://discord.gg/qxnd5XjD

**Comment by kanerogers** [comment]
@pierre-l Great news! With #119 merged, you should now be able to get the example running on the Quest 1. 😄 

Let me know how you go!

**Comment by pierre-l** [comment]
@kanerogers Victory! Cubes are displayed, I can control the sabers, this is awesome! Thanks for the fix! I'll see you on Discord :)

**Comment by kanerogers** [comment]
> @kanerogers Victory! Cubes are displayed, I can control the sabers, this is awesome! Thanks for the fix! I'll see you on Discord :)

Yay! 😁

**Comment by jam1garner** [comment]
@kanerogers just as another bullet point to help you check off another box: building on linux (`Ubuntu 20.04.3 LTS x86_64`) without issue*.

\*excluding the bug I've seen in other XR projects regarding needing to reinstall every run. but that's not really relevant to being able to build on linux
